# This workflow deploys to PyPi

name: Deploy to PyPi

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "hello-world-main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "test_pull_request"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Setup Python
      - name: Setup Python
        uses: actions/setup-python@v4.2.0
        with:
          python-version: 3.10.6
      
      # Setup Poetry
      - name: Setup Poetry
        uses: Gr1N/setup-poetry@v7
        
      # Install Dependencies
      - run: poetry install
      
      # Build Package
      - run: poetry build

      # Deploy to PyPi
      - run: poetry publish -u __token__ -p ${{ secrets.PYPI_TOKEN }}
