# This workflow builds & deploys API documentation on pull requests to the main branch.

name: Publish API Documentation

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ['main']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Give the action the permission it needs
permissions:
  contents: write

# Set the working directory to docs
defaults:
  run:
    working-directory: docs

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "publish_api"
  publish_api:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Setup Python
      - name: Setup Python
        uses: actions/setup-python@v4.2.0
        with:
          python-version: 3.10.6

      # Setup Poetry
      - name: Setup Poetry
        uses: Gr1N/setup-poetry@v7

      # Install Dependencies
      - run: poetry install

      # Build API Documentation
      - run: poetry run sphinx-apidoc -o . ..
      - run: poetry run make html

      # Deploy API Documentation
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs/_build/html # The folder the action should deploy.
          branch: gh-pages # The branch the action should deploy to.
